---

- name: check if EPEL repo is already configured
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
  tags:
    - epel
 
- name: install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
  tags:
    - epel
 
- name: import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  tags:
    - epel
  