---

- name: populate mariadb repo file
  template: src=MariadDB.repo.j2 dest=/etc/yum.repos.d/MariadDB.repo owner=root group=root mode=0640
  tags:
    - mariadb
  
- name: install mariadb
  yum: name=MariaDB-server state=present update_cache=yes disable_gpg_check=yes validate_certs=no
  tags:
    - mariadb
    - yum

- name: create directory for logs
  file: path=/var/log/mysql state=directory owner=mysql
  tags:
    - mariadb

- name: populate /etc/my.cnf.d/server.cnf
  template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf mode=0644
  tags:
    - mariadb
    - config
 
- name: ensure mariadb is running and started at boot
  service: name=mariadb enabled=yes state=started
  tags:
    - mariadb
  