---

- include_tasks: vendor.yml
  loop: "{{ xcloud_versions | dict2items }}"
  loop_control:
    loop_var: vendor
  tags:
    - xcloud
    - apps

- name: install /etc/motd
  template: src=motd.j2 dest=/etc/motd
  tags:
   - xcloud
