---

- name: install packages
  yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes validate_certs=no
  with_items: "{{ setup_packages }}"
  tags:
    - setup
    - yum

- name: disable firewalld
  service: name=firewalld enabled=no state=stopped
  tags:
    - setup
    - firewalld

- name: set selinux to permissive
  selinux: policy=targeted state=permissive
  tags:
    - setup
  