---

- name: install memcached
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ memcached_packages }}"
  tags:
    - memcached
    - yum

- name: populate /etc/sysconfig/memcached
  template: src=memcached.j2 dest=/etc/sysconfig/memcached owner=root group=root mode=0644
  notify:
    - reload memcached
  tags:
    - memcached

- name: ensure memcached is running and started at boot
  service: name=memcached state=started enabled=yes
  tags:
    - memcached

